<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="td1"
    nsURI="http://www.example.org/td1"
    nsPrefix="td1">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="State">
    <eOperations
        name="StateInvariant"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="outTransition"
        lowerBound="1"
        upperBound="-1"
        eType="#//Transition"
        eOpposite="#//Transition/source"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="inTransition"
        lowerBound="1"
        upperBound="-1"
        eType="#//Transition"
        eOpposite="#//Transition/target"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Process">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="transition"
        lowerBound="1"
        upperBound="-1"
        eType="#//Transition"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variable"
        upperBound="-1"
        eType="#//Variable"
        eOpposite="#//Variable/process"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="init"
        lowerBound="1"
        eType="#//Init"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="states"
        lowerBound="1"
        upperBound="-1"
        eType="#//State"
        containment="true"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Transition">
    <eOperations
        name="Guard"/>
    <eOperations
        name="Trigger"/>
    <eOperations
        name="Action"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="source"
        lowerBound="1"
        eType="#//State"
        eOpposite="#//State/outTransition"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="target"
        lowerBound="1"
        eType="#//State"
        eOpposite="#//State/inTransition"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="DataType"/>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Variable">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="datatype"
        lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="process"
        upperBound="-1"
        eType="#//Process"
        eOpposite="#//Process/variable"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="component"
        upperBound="-1"
        eType="#//Component"
        eOpposite="#//Component/variable"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Init">
    <eOperations
        name="Assignment"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="initialState"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ECharacterObject"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Component">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="process"
        lowerBound="1"
        upperBound="-1"
        eType="#//Process"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variable"
        upperBound="-1"
        eType="#//Variable"
        eOpposite="#//Variable/component"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="ID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Program">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="component"
        lowerBound="1"
        upperBound="-1"
        eType="#//Component"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="variable"
        upperBound="-1"
        eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="process"
        lowerBound="1"
        upperBound="-1"
        eType="#//Process"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
